version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions-deps:
        patterns:
          - "*"
    target-branch: "deploy"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/api"
      - "/packages/web"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    target-branch: "deploy"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
