services:
  webserver:
    build: .
    container_name: grizzlyrobotics.org
    env_file:
      - .env

    image: grizzlyrobotics.org:0.0.1
    ports:
      - "5100:5100"

    pull_policy: build
    restart: always
