name: Deploy

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    environment:
      name: Production
      url: ${{ steps.vercel.outputs.preview-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Trigger deployment
        uses: amondnet/vercel-action@v42.3.0
        id: vercel
        with:
          vercel-version: 50.44.0
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
