name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ deployments ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions: 
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install Vercel CLI
        run: npm i vercel

      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Vercel Project
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Start GitHub Deployment
        id: deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Deploy
        run: |
          URL=$(npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} | tail -n1)
          echo "ENV_URL=$URL" >> $GITHUB_OUTPUT

      - name: Update GitHub Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.vercel_deployment.outputs.ENV_URL }}
          env: production
      
      - name: Promote Build
        run: npx vercel promote ${{ steps.vercel_deployment.outputs.ENV_URL }} --token=${{ secrets.VERCEL_TOKEN  }} --scope=${{ secrets.VERCEL_ORG_ID }} --yes
